### ISSUE TITLE
Chfast's fork doesn't compile directly

### ISSUE THREAD

**Issue by golyalpha** [ludbb/secp256k1-py#13]
When I install the secp256k1-transient, I have no problems whatsoever, but when I try to install if from git doing this in requirements.txt:

> git+https://github.com/chfast/secp256k1-py.git@fe39e4c#egg=secp256k1

 
I get this error:

> cffi.ffiplatform.VerificationError: LinkError: command 'C:\\Users\\[user_name]\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\link.exe' failed with exit status 1181

@chfast

**Comment by ludbb** [comment]
That's a fork, not a branch. Contact the fork owner directly please.

**Comment by golyalpha** [comment]
I wanted to make an issue on his fork, cannot...
