### ISSUE TITLE
Wheels?

### ISSUE THREAD

**Issue by AdamISZ** [ludbb/secp256k1-py#14]
I'm not au fait with the details, but I was under the impression that there would be wheels [here](https://pypi.python.org/pypi/secp256k1) after the PR #12 ?

**Comment by ludbb** [comment]
Sorry, I believe there was some confusion as #12 builds wheels only for Linux, which is available now. If you want to adjust travis.yml and .travis/deploy.sh to build it for OSX, the PR will be welcomed.

Also, deploying automatically via Travis has the problem mentioned in that PR. It does leak the credentials in the build output, so I had to change the password on the account used after building it (and if anyone watches it while it's building they can take over the account). So before doing more deployments using the script method, I or someone else need to figure out a way to pass the password to twine using a different method.

**Comment by AdamISZ** [comment]
Thanks, they appear to have been uploaded yesterday. Re: credentials, thanks for that explanation.
