### ISSUE TITLE
[libsecp256k1] illegal argument: Invalid flags

### ISSUE THREAD

**Issue by instagibbs** [ludbb/secp256k1-py#4]
Getting this whenever I run any of the examples dealing with secp256k1_context_create. 

The values being passed in look right (1/2/3). Ideas?

edit: Realized I'm getting the same issue on my random code now too. Maybe connected to me updating the base library.

**Comment by ludbb** [comment]
Are you running the latest bitjws version? This is what happens when I use an invalid flag:

```python
>>> from secp256k1 import PrivateKey
>>> PrivateKey(flags=4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "secp256k1.py", line 318, in __init__
    assert flags in (ALL_FLAGS, FLAG_SIGN)
AssertionError
```

If it fails for valid flags then your reason in the edit section seems like it. Make sure you're using the latest version of the underlying C secp256k1 library.

**Comment by instagibbs** [comment]
Seems related to this: https://github.com/bitcoin/secp256k1/commit/9234391ed4d5fae38921a8bb4ca36f9f33736fd7#diff-0d77700fa6e05639431c962ffaa5365aR65 

It's tripping up on line 65 of the main c file.

**Comment by ludbb** [comment]
Ah, it turns out I wasn't running the latest latest version. The flag constants changed, so this wrapper needs to be updated. Doing it now.

**Comment by instagibbs** [comment]
I would've tried but on business phone call while doing this ;)  thanks

**Comment by ludbb** [comment]
https://github.com/ludbb/secp256k1-py/commit/c44fed6a7c0d3b44a8398668aa5f4015297f9d55 fixed it. If you installed via pypi, please run `pip install -U secp256k1` to get the 0.11.0 version that contains the fix.

**Comment by instagibbs** [comment]
Great! Seems to be working on my end.

**Comment by ludbb** [comment]
Thanks for checking!
