### ISSUE TITLE
undefined symbol: secp256k1_ecdsa_recoverable_signature_parse_compact

### ISSUE THREAD

**Issue by czepluch** [ludbb/secp256k1-py#5]
When trying to run the following from the same dir that I have the test suite passing, I get this error. Which is very weird since the tests are passing. Maybe I have installed in a wrong way, but have tried both through pip and by cloning your repo and installing it manually.

```
$ python -m secp256k1 privkey -p                                               
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "~/ludbb_secp256k1/secp256k1-py/secp256k1.py", line 5, in <module>
    from _libsecp256k1 import ffi, lib
ImportError: ./_libsecp256k1.so: undefined symbol: secp256k1_ecdsa_recoverable_signature_parse_compact
```

**Comment by czepluch** [comment]
Okay. It seems I need to have `LD_LIBRARY_PATH=./secp256k1/.libs LIB_DIR=./secp256k1/.libs INCLUDE_DIR=./secp256k1/include` in front of `python -m secp256k1 privkey -p` in order for it to work.

**Comment by ludbb** [comment]
Thank you, did you install the secp256k1 dependency somewhere in your library path? If you did then setting your library path shouldn't be necessary.

**Comment by czepluch** [comment]
Thought I did, but apparently I didn't.

**Comment by jeteon** [comment]
Setting the variables before the invocation didn't seem to help for me. I didn't actually install the library into the system as I just wanted to evaluate it without making a permanent system change for now. Do you know where that symbol is defined?
