### ISSUE TITLE
Don't create secp256k1_context in constructor

### ISSUE THREAD

**Issue by AdamISZ** [ludbb/secp256k1-py#9]
See: https://github.com/bitcoin/secp256k1/blob/master/include/secp256k1.h#L31-L33

I found that removing the context object from the constructor [here](https://github.com/ludbb/secp256k1-py/blob/master/secp256k1/__init__.py#L27) and making it a module level var, made the code run massively faster when dealing with a lot of keys (as you'd expect, I think).

**Comment by AdamISZ** [comment]
Apologies, now I look at the code again I can see that passing in the context is an option in the constructor. 

Perhaps there might still be an issue/consideration here in as much as people might not notice how important this is for performance.

**Comment by ludbb** [comment]
It's the most expensive thing you can do here, you're right. Do you want to suggest edits to README? Would that be enough?

**Comment by AdamISZ** [comment]
I was wondering whether removing the default is a good idea (i.e. requiring the caller to provide it); but I'm not at all sure, don't have a strong opinion about it.

**Comment by ludbb** [comment]
Closing as it has been open for a long time without progress, thanks for reporting.
